spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:cafemgmtsys_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:By@$hna%}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: badsnastha@gmail.com
    password: nadgdjczmtvgdiox
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-message: always








